rules:
  # checks if file ends in a newline character
  end-of-file:
    # set to true to enable this rule
    enable: true

    # set to true to disable autofix (if enabled globally)
    disable-autofix: true

    # will be ignored only by this rule
    ignore:
      - README.md
      - .github/workflows/pr_files_comparision.yml
      - .github/workflows/staging_pr_ci.yml
      - .github/workflows/prod_deployment.yml
      - .github/workflows/staging_tag_creation.yml
      - .linelint.yml
      - .pylintrc

    # if true also checks if file ends in a single newline character
    single-new-line: false