name: Slack Pull Request Open Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: shell run
      run: |
        date
        ls -l
    #- name: Notify slack pr open
    #  env: 
    #    SLACK_WEBHOOK_URL : ${{ secrets.SLACK_WEBHOOK_URL }}
    #    PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }}
    #    PULL_REQUEST_TITLE : ${{ github.event.pull_request.title }}
    #    PULL_REQUEST_AUTHOR_NAME : ${{ github.event.pull_request.user.login }}
    #    PULL_REQUEST_AUTHOR_ICON_URL : ${{ github.event.pull_request.user.avatar_url }}
    #    PULL_REQUEST_URL : ${{ github.event.pull_request.html_url }}
    #    PULL_REQUEST_BODY : ${{ github.event.pull_request.body }}
    #    PULL_REQUEST_COMPARE_BRANCH_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
    #    PULL_REQUEST_COMPARE_BRANCH_NAME : ${{ github.event.pull_request.head.ref }}
    #    PULL_REQUEST_BASE_BRANCH_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
    #    PULL_REQUEST_BASE_BRANCH_NAME : ${{ github.event.pull_request.base.ref }}
    #    IS_SEND_HERE_MENTION : true
    #    MAKE_PRETTY : false
    #    MAKE_COMPACT : false
    #    IS_PR_FROM_FORK: false
    #    SEND_USER_ID_MENTIONS : ABCDE12345,AAABBBCCCC
    #    SEND_GROUP_ID_MENTIONS : GROUPIDDDD,GGGGROUPID
    #  uses: jun3453/slack-pr-open-notification-action@v1.3.0

    - name: slack-notify
      uses: ravsamhq/notify-slack-action@v1
      if: always()
      with:
        status: ${{ job.status }}
        notification_title: 'New pull-request ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} has been raised agaist ${GITHUB_REF#refs/heads/} from branch ${{ github.event.pull_request.base.ref }}'
        message_format: 'Review and approve PR for staging deployment'
      env:  
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}