name: PR files
on:
  pull_request:
    branches:
      - tprd

env:
  from_branch: ${{ github.event.pull_request.head.ref }}
  to_branch: ${{ github.event.pull_request.base.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.G_TOKEN }}
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6

      - name: File comparision
        id: comparision
        run: |
          git remote set-url origin https://${{ secrets.G_TOKEN }}@github.com/vinothgitkumar/branching-demo.git
          git fetch --all
          from_branch_name=`echo "${from_branch}"`
          to_branch_name=`echo "${to_branch}"`
          git switch -c $from_branch_name origin/$from_branch_name
          git checkout tstg
          git pull origin tstg --tags
          latest_tag_name=`git tag --sort version:refname | grep "$from_branch_name" | tail -n1`
          REGEX="^[a-zA-Z0-9.-]+$"
          if [[ "$tag_find" =~ $REGEX ]]; then
            echo "Latest tag is $latest_tag_name"
            git checkout -b temp-${from_branch} $latest_tag_name
            new_branch=temp-${from_branch}
            echo "New branch is $new_branch"
            COUNT_VAR=0
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              diff_result=`git diff $from_branch_name:$file $new_branch:$file`
              if [ -z "$diff_result" ]
              then
                    echo "$file content is same in both $from_branch_name branch and same commit in $to_branch_name branch"
              else
                    echo "$file content differs while comparing in $from_branch_name branch and $to_branch_name branch"
                    COUNT_VAR=$((COUNT_VAR+1))
              fi 
            done
            
            if [[ $COUNT_VAR == "0" ]]; then
              echo ::set-output name=differs::false
            else
              echo ::set-output name=differs::true
            fi
  
            echo "COUNT_VAR=$COUNT_VAR" >> $GITHUB_ENV

          else
            echo ::set-output name=tagging::notag

          fi



      - name: Slack notification
        if: ${{ steps.comparision.outputs.differs == 'true' }}
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: 'Files Differ:'
          message_format: 'Files in PR differs while comparing it with ${{ github.event.pull_request.head.ref }} branch and tstg branch ${{ steps.comparision.outputs.tag_name }} tag commit'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack notification
        if: ${{ steps.comparision.outputs.differs == 'false' }}
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: 'Files Not Differ:'
          message_format: 'Files in PR not differs hence Please approve the PR'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack notification
        if: ${{ steps.comparision.outputs.tagging == 'notag' }}
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: 'New Feature Branch:'
          message_format: 'No commits found on Staging branch from this feature branch hence please create PR against staging first'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}