name: Production Deployment Workflow
on:
  pull_request:
    branches:
      - tprd
    types: [closed]

env:
  from_branch: ${{ github.event.pull_request.head.ref }}
  to_branch: ${{ github.event.pull_request.base.ref }}

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.G_TOKEN }}
          fetch-depth: 0

      - name: Production Deployment
        id: prod_deploy
        run: |
          echo "Prod deployment"

      - name: Delete Feature Branch
        if: steps.prod_deploy.outcome == 'success'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.G_TOKEN }}
          branches: ${{ github.event.pull_request.head.ref }}

      - name: Delete Feature Branch's Tags in Github
        if: steps.prod_deploy.outcome == 'success'
        run: |
          git remote set-url origin https://${{ secrets.G_TOKEN }}@github.com/vinothgitkumar/branching-demo.git
          git fetch --all
          from_branch_name=`echo "${from_branch}"`
          to_branch_name=`echo "${to_branch}"`
          git switch -c tstg origin/tstg
          git pull origin tstg --tags
          tag_list=`git tag --sort version:refname | grep "$from_branch_name"`
          for tags in $tag_list; do
            echo $tags
            git push --delete origin $tags
          done