name: Production Deployment Workflow
on:
  pull_request:
    branches:
      - tprd
    types: [closed]

env:
  from_branch: ${{ github.event.pull_request.head.ref }}
  to_branch: ${{ github.event.pull_request.base.ref }}

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.G_TOKEN }}
          fetch-depth: 0

      - name: Production Deployment
        id: prod_deploy
        run: |
          echo "Prod deployment"

      - name: Delete Production Branch
        if: steps.prod_deploy.outcome == 'success'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.G_TOKEN }}
          branches: ${from_branch}